name: CD-BBDD
on:
  push:
    branches: ['main']
    paths:
      - 'docker-compose-db.yml'
  workflow_dispatch:

jobs:
  cd-bbdd:
    name: Deploy Postgres Database on AWS Lightsail
    runs-on: ubuntu-22.04
    steps:
      - name: 🐘 Deploy Postgres
        uses: appleboy/ssh-action@8faa84277b88b6cd1455986f459aa66cf72bc8a3 # v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP_MAIN }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER_MAIN }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY_MAIN }}
          script: |
            sudo docker network inspect devopsNet >/dev/null 2>&1 || sudo docker network create devopsNet

            sudo docker rm -f postgres || true
            sudo docker volume create postgres-data >/dev/null 2>&1 || true
            sudo docker run -d \
              --name postgres \
              --restart always \
              --network devopsNet \
              -p 5432:5432 \
              -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
              -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
              -e POSTGRES_DB=iwvgdevopsdb \
              -v postgres-data:/var/lib/postgresql/data \
              postgres:15.10

            echo "⏳ Esperando a que Postgres esté listo"
            for i in $(seq 1 6); do
              sleep 5
              sudo docker exec postgres pg_isready -U "${{ secrets.POSTGRES_USER }}" && break
            done
